In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###different types of Tensors


In [2]:
#scalar Tensor
scalar=torch.tensor(7)
#Tensors in pytorch are created using torch.tensor()
scalar

tensor(7)

In [3]:
print(f"scalar.item() converts tensors to python integers -> {scalar.item()}")
print(f"scalar.ndim gives dimension of the tensor named scalar -> {scalar.ndim}")

scalar.item() converts tensors to python integers -> 7
scalar.ndim gives dimension of the tensor named scalar -> 0


In [4]:
#vector tensor
vector=torch.tensor([7,7])
print(f"dimensions of vector -> {vector.ndim}")
print(f"shape of a vector -> {vector.shape}")

dimensions of vector -> 1
shape of a vector -> torch.Size([2])


In [5]:
#MATRIX
matrix=torch.tensor([[7,8],
                    [9,10]])
print(f" generally capital letter used \n M = {matrix}")
print(f"dimensions of the matrix->{matrix.ndim}")
print(f"shape of a matrix ->{matrix.shape}")
print(f"0th axis -> {matrix[0]}")
print(f"1st axis ->{matrix[1]}")

 generally capital letter used 
 M = tensor([[ 7,  8],
        [ 9, 10]])
dimensions of the matrix->2
shape of a matrix ->torch.Size([2, 2])
0th axis -> tensor([7, 8])
1st axis ->tensor([ 9, 10])


according to dimension they may be called scalar,vector or matrix but they all are torch.tensor


In [6]:
#TENSOR
T=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [5,6,7]]])
print(f"generally capital letter used \n T={T}")
print(f"dimensions of the tensor->{T.ndim}")
print(f"shape of the tensor->{T.shape} meaning we have 1 3*3 matrix")
print("tensor[1][0] goes out of bounds")
print(f"since python is 0 indexed for shape ([1,3,3]) first element in tensor([must be 0 ][row of matrix][column of matrix])-> \n {T[0][0]}")

generally capital letter used 
 T=tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 6, 7]]])
dimensions of the tensor->3
shape of the tensor->torch.Size([1, 3, 3]) meaning we have 1 3*3 matrix
tensor[1][0] goes out of bounds
since python is 0 indexed for shape ([1,3,3]) first element in tensor([must be 0 ][row of matrix][column of matrix])-> 
 tensor([1, 2, 3])


###Random Tensors
-> used to initialize weights and then they are adjusted to better represent the data

In [7]:
#creating random tensors of size (1,3,4)
random_tensor=torch.rand(1,3,4)
#can be written as random_tensor=torch.rand(size=(1,3,4))
print(random_tensor)
print(f"dimensions of the tensor->{random_tensor.ndim}")
print(f"shape of the tensor->{random_tensor.shape}")


tensor([[[0.5345, 0.3765, 0.1635, 0.1171],
         [0.1145, 0.2451, 0.2093, 0.4989],
         [0.7965, 0.9660, 0.8182, 0.4232]]])
dimensions of the tensor->3
shape of the tensor->torch.Size([1, 3, 4])


In [8]:
#creating a random tensor similar to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
print(random_image_size_tensor)
print("torch.randn(size=(height,width,color_channel))")
print(f"dimensions of the tensor->{random_image_size_tensor.ndim}")
print(f"shape of the tensor->{random_image_size_tensor.shape}")

tensor([[[0.4713, 0.7874, 0.4903],
         [0.8650, 0.5663, 0.0722],
         [0.3727, 0.5604, 0.4701],
         ...,
         [0.0432, 0.3553, 0.9880],
         [0.6020, 0.2506, 0.7585],
         [0.0878, 0.2040, 0.5563]],

        [[0.4963, 0.8081, 0.6471],
         [0.7895, 0.2265, 0.1519],
         [0.9502, 0.2248, 0.1021],
         ...,
         [0.8611, 0.2774, 0.9937],
         [0.3926, 0.2762, 0.3110],
         [0.5953, 0.6933, 0.8709]],

        [[0.5560, 0.6429, 0.8381],
         [0.7903, 0.1599, 0.9872],
         [0.3426, 0.0309, 0.2401],
         ...,
         [0.5570, 0.8504, 0.1143],
         [0.4470, 0.5304, 0.1134],
         [0.4259, 0.0300, 0.9345]],

        ...,

        [[0.6197, 0.6938, 0.6832],
         [0.2176, 0.0879, 0.4569],
         [0.0735, 0.6951, 0.0240],
         ...,
         [0.7126, 0.5616, 0.0265],
         [0.4986, 0.8269, 0.1702],
         [0.2248, 0.6971, 0.7589]],

        [[0.6483, 0.3733, 0.8235],
         [0.5328, 0.8519, 0.2296],
         [0.

In [9]:
# zeros and ones tensor
#used to create masks
zero_tensor=torch.zeros(1,3,4)
print(zero_tensor)
ones_tensor=torch.ones(1,3,4)
print(ones_tensor)
print(f"default data type = {ones_tensor.dtype}")

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
default data type = torch.float32


In [10]:
#creating a range of tensors and tensor-likes
one_to_ten=torch.arange(start=1,end=11,step=2)
print(one_to_ten)

tensor([1, 3, 5, 7, 9])


In [12]:
ten_zeros=torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0])


###TENSOR DATATYPES

> **NOTE:** tensor dtypes one of 3 big errors with deeplearning and Pythorch
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device



In [21]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
print(f"default datatype {float_32_tensor.dtype}")
print("32 bit is single precision and 16 bit is half precision")

default datatype torch.float32
32 bit is single precision and 16 bit is half precision


In [23]:
float_16_tensor=torch.tensor([3,6,9],dtype=torch.float16,#datatype of tensor
                             device=None,#what device is tensor on
                             requires_grad=False #whether or not to track tensor operations
                             )
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [30]:
#convert tensor float_32_tensor to half precision
float_half=float_32_tensor.type(torch.half)

In [34]:
##sometimes different data types can still be multiplied
product=float_32_tensor * float_16_tensor
print(product)

tensor([ 9., 36., 81.])


In [40]:
#change device from CPU to GPU
float_32_tensor.to(device="cuda")

AssertionError: Torch not compiled with CUDA enabled

###getting info from tensors
1. to get dtype from a tensor -> tensor.dtype
2. to get shape from a tensor -> tensor.shape or tensor.size()
3. to get device from a tensor -> tensor.device