<a href="https://colab.research.google.com/github/ShreyashDhoot/learning-pytorch/blob/main/notebook2_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Tensor Operations
1. addition
2. subtraction
3. element wise multiplication
4. division
5. matrix multiplication



In [2]:
#create tensor and add 10
tensor=torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [3]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [4]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [5]:
print(f"torch.mul(tensor,10)={torch.mul(tensor,10)}")
print(f"torch.add(tensor,10)={torch.add(tensor,10)}")

torch.mul(tensor,10)=tensor([10, 20, 30])
torch.add(tensor,10)=tensor([11, 12, 13])


### Matrix multiplication
2 main ways to do matrix multiplication in ML and DL
1. element wise matric multiplication
2. matrix multiplication (dot product)

In [6]:
## element wise
tensor_a=torch.rand(3,3)
tensor_b=torch.rand(3,3)
print(tensor_a)
print(tensor_b)
print(f"proof look at left corner element of both the matrix \n {tensor_a[0][0]:.4g}*{tensor_b[0][0]:.4g}={tensor_a[0][0] * tensor_b[0][0]:.4g}")
print(tensor_a*tensor_b)

tensor([[0.2830, 0.5996, 0.4399],
        [0.8314, 0.9464, 0.4945],
        [0.9650, 0.4952, 0.2440]])
tensor([[0.2226, 0.2599, 0.3120],
        [0.5417, 0.1448, 0.6136],
        [0.4408, 0.7659, 0.5865]])
proof look at left corner element of both the matrix 
 0.283*0.2226=0.06301
tensor([[0.0630, 0.1558, 0.1373],
        [0.4503, 0.1370, 0.3034],
        [0.4254, 0.3792, 0.1431]])


In [7]:
#matrix multiplication
tensor_1=torch.rand(3,4)
tensor_2=torch.rand(4,3)
## matmul is depricated so use torch.mm
new_tensor=torch.mm(tensor_1,tensor_2)
print(new_tensor.size())
print(new_tensor)

torch.Size([3, 3])
tensor([[1.4934, 0.6643, 0.8450],
        [1.5623, 0.8294, 1.0951],
        [1.1566, 0.5959, 0.7977]])


In [8]:
#shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
##using a transpose we can multiply these
print(f"Tensor B-> {tensor_B.shape} \n {tensor_B}")
print(f"transpose of Tensor B-> {tensor_B.T.shape} \n {tensor_B.T}")
torch.mm(tensor_A,tensor_B.T)

Tensor B-> torch.Size([3, 2]) 
 tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
transpose of Tensor B-> torch.Size([2, 3]) 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Finding Tensor Aggregation
1.min
2.max
3.mean
4.sum

In [10]:
x=torch.arange(0,101,10)
print(x)
print(torch.min(x))
print(x.min())
print(torch.max(x))
print(x.max())

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
tensor(0)
tensor(0)
tensor(100)
tensor(100)
tensor(50.)


In [11]:
#torch.mean requires a tensor of float32 datatype to work
print(torch.mean(x.type(torch.float32)))

tensor(50.)


In [12]:
#sum of all values in the tensor
torch.sum(x)

tensor(550)

###Positional Max and Min
1. Argmin - provides argument or index position in tensor with max value

2. Argmax - provides argument or index position in tensor with min value

Helpful when using softmax function

In [14]:
torch.argmax(x)

tensor(10)

In [15]:
torch.argmin(x)

tensor(0)

### Reshaping , stacking , Squeezing and unsqueezing
1. Reshaping - reshpaes an input to a definite shape
2. view - return the view of an input tensor of certain shape but keep ythe same memory as the original tensor
3. Stacking- combining multiple tensors on each other (v.stack-> vertical stack ) (h.stack-> horizontal stack )
4. Squeeze - removes all '1' dimensions from a tensor
5. Unsqueeze - add a '1' dimension to the tensor
6. Permute - return a view of the input with the dimension permuted (swapped) in a certain way

In [29]:
x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [30]:
# add an extra dimension
# reshape has to be compatible with the number of elements
x_reshape = x.reshape(1,9)
x_reshape,x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [31]:
# change the view
# z is just a different view of x
# changing view of z changes x
z=x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [44]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [55]:
#squeeze
x_squeezed=torch.squeeze(x_stacked,dim=0)
x_squeezed,x_squeezed.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [57]:
#unsqueeze
x_unsqueeze=torch.unsqueeze(x_squeezed,dim=0)
x_unsqueeze, x_unsqueeze.size()

(tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9],
          [1, 2, 3, 4, 5, 6, 7, 8, 9]]]),
 torch.Size([1, 4, 9]))

In [75]:
#permute
torch.permute(x_unsqueeze,(0,1,2))

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [61]:
torch.permute(x_unsqueeze,(1,0,2))

tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [81]:
x_original=torch.rand(size=(224,224,3))
# permute the original tensor to rearrage the axis (or dim) order
x_permuted=x_original.permute(2,0,1)
print("previous shape :\n")
print(x_original.size())
print("permuted shape :\n")
print(x_permuted.size())

previous shape :

torch.Size([224, 224, 3])
permuted shape :

torch.Size([3, 224, 224])


### Indexing with Tensors

In [83]:
a=torch.arange(1,10).reshape(1,3,3)
a,a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [92]:
a[0],a[0][0],a[0][1],a[0][1][1],a[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor([4, 5, 6]),
 tensor(5),
 tensor(6))

In [97]:
a[:,:,2]

tensor([[3, 6, 9]])

##Pytorch tensors and NumPy

In [101]:
##Numpy array to pytorch tensor
array = np.arange(1.,8.)
tensor=torch.from_numpy(array) #warning- when converting from numpy to pytorch, it reflects the numpy's default datatype of float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

### REproducibility

In [116]:
## Reproducibility taking random out of random
## only works for cell it is in
random_seed=42
torch.manual_seed(random_seed)
random_tensor_c=torch.rand(3,4)
print(random_tensor_c)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
